added network modules
Signed-off-by: Lalith Panditharatne <Lalith@access-is.com>

diff --git a/mkupdatepkg b/mkupdatepkg
--- a/mkupdatepkg
+++ b/mkupdatepkg
@@ -1,6 +1,13 @@
 #!/bin/bash
 #
 # create update package
+
+
+if [ ! -d tar-install ] ; then 
+	echo "tar-install dir not found, first do "make tar-pkg" target. run build.sh first" 
+	exit 1
+fi
+
 if [ -d upgrade ] ; then rm -rf upgrade ; fi 
 if [ -f upgrade*.tar.xz ] ; then rm -rf upgrade*.tar.xz ; fi 
 mkdir tmp upgrade
@@ -15,10 +22,25 @@ if [ -z "$dtbfile" ]; then
     rm -rf upgrade
     exit 1;
 fi
-cp -a arch/arm/boot/zImage upgrade/
-cp -a arch/arm/boot/dts/$dtbfile upgrade/
+if [ -f arch/arm/boot/zImage ] ; then 
+	cp -a arch/arm/boot/zImage upgrade/
+else
+	echo "zImage not foud, build kernel first, aborting"
+	rm -rf upgrade
+    exit 1;
+fi 
+
+if [ -f arch/arm/boot/dts/$dtbfile ] ; then 
+	cp -a arch/arm/boot/dts/$dtbfile upgrade/
+else
+	echo "device tree file not built, aborting"
+	rm -rf upgrade
+    exit 1;
+fi 
+
 fakeroot chown -R root.root upgrade/
 fakeroot md5sum upgrade/* > upgrade/MD5SUM
 tar -cJf upgrade-$gitrev.tar.xz upgrade
 
 echo "update package created : upgrade-$gitrev.tar.xz"
+exit 0
